### ISSUE TITLE
add notification when bot crashes

### ISSUE THREAD

**Issue by shaunagm** [shaunagm/WelcomeBot#10]
Right now the WelcomeBot stops running at seemingly random times and sits there, quietly, until someone notices and reminds me to log into the server and restart it.  It would be nice if I got an email notification or something similar when WelcomeBot stopped running.

**Comment by pdurbin** [comment]
Some thoughts from @prologic on possible issues handling PING/PONG with freenode: http://irclog.perlgeek.de/crimsonfu/2015-04-02

**Comment by prologic** [comment]
See: https://github.com/circuits/circuits/blob/master/circuits/protocols/irc/protocol.py#L88

You **must** respond like this:

SERVER:
```
PING :1234
```

CLIENT:
```
PONG :1234
```

Whatever arguments/data you see in the ``PONG`` request you must respond with using ``PONG`` and the arguments/data you see **as-is** (*exactly*).

**Comment by shaunagm** [comment]
Thanks for the help, @prologic!  I've implemented a fix here:

https://github.com/shaunagm/WelcomeBot/commit/6e2555794681155469349616352fdf1395995b14

I've also got a script set up to catch the bot when it crashes:
    /usr/bin/screen -S WelcomeBot /bin/bash
    while true; do
      nohup python bot.py >> error.out
    done &

Hopefully between these two things, the bot will be more stable.  If not, I'll reopen the issue.
